//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use serde::{Deserialize, Serialize};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "likes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub note_metadata_id: i32,
    pub ip_address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::notes_metadata::Entity",
        from = "Column::NoteMetadataId",
        to = "super::notes_metadata::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    NotesMetadata,
}

impl Related<super::notes_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotesMetadata.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
